fint:
  application-id: fint-flyt-intgr-conf-service

server:
  error:
    include-message: always

spring:
  profiles:
    include:
      - flyt-logging
      - flyt-postgres
      - flyt-kafka
      - flyt-web-resource-server
      - flyt-authorization-client
  output:
    ansi:
      enabled: always
